global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
  
  - job_name: 'galaxydevelopers'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'