#!/bin/bash

# Обработка через Gemini из контура GalaxyDevelopers
# Адаптированная версия для работы из нашей системы

# Загружаем конфигурацию
source "$(dirname "$0")/config.sh"

# Проверяем аргументы
if [ $# -lt 2 ]; then
    echo "Использование: $0 <файл_или_папка> <промпт>"
    echo "Пример: $0 /path/to/file.txt 'Проанализируй этот код'"
    exit 1
fi

INPUT_PATH="$1"
PROMPT="$2"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

# Проверяем API ключ
if ! check_gemini_api; then
    echo "Установите GEMINI_API_KEY:"
    echo "export GEMINI_API_KEY='your-api-key'"
    exit 1
fi

# Определяем выходной файл
OUTPUT_FILE="$GEMINI_OUTPUTS/gemini_${TIMESTAMP}.md"

gemini_log "🚀 Запуск обработки через Gemini"
gemini_log "📁 Вход: $INPUT_PATH"
gemini_log "💬 Промпт: $PROMPT"

# Функция обработки файла через Gemini
process_with_gemini() {
    local content="$1"
    local prompt="$2"
    
    # Ограничиваем размер контента (30KB для Gemini)
    content=$(echo "$content" | head -c 30000)
    
    # Экранируем специальные символы
    content=$(echo "$content" | sed 's/"/\\"/g' | tr '\n' ' ')
    prompt=$(echo "$prompt" | sed 's/"/\\"/g')
    
    # Отправляем запрос к Gemini
    response=$(curl -s \
        -H "Content-Type: application/json" \
        -d "{
            \"contents\": [{
                \"parts\": [{
                    \"text\": \"${prompt}\\n\\n${content}\"
                }]
            }]
        }" \
        "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=$GEMINI_API_KEY")
    
    # Извлекаем текст из ответа
    echo "$response" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    text = data.get('candidates', [{}])[0].get('content', {}).get('parts', [{}])[0].get('text', 'No response')
    print(text)
except:
    print('Error parsing response')
"
}

# Обработка в зависимости от типа входа
if [ -f "$INPUT_PATH" ]; then
    # Это файл
    gemini_log "📄 Обработка файла: $(basename "$INPUT_PATH")"
    
    content=$(cat "$INPUT_PATH")
    result=$(process_with_gemini "$content" "$PROMPT")
    
    # Сохраняем результат
    cat > "$OUTPUT_FILE" << EOF
# Gemini Analysis Result
**Date**: $(date)
**File**: $INPUT_PATH
**Prompt**: $PROMPT

---

## Result:

$result

---
*Generated by GalaxyDevelopers Gemini System*
EOF
    
elif [ -d "$INPUT_PATH" ]; then
    # Это папка
    gemini_log "📁 Обработка папки: $INPUT_PATH"
    
    # Собираем все текстовые файлы
    combined_content=""
    file_count=0
    
    for file in "$INPUT_PATH"/*.{txt,md,py,js,sh,json} 2>/dev/null; do
        if [ -f "$file" ]; then
            ((file_count++))
            filename=$(basename "$file")
            gemini_log "  • Добавляю: $filename"
            
            combined_content+="\\n\\n=== FILE: $filename ===\\n"
            combined_content+=$(cat "$file" | head -c 5000)  # Лимит на файл
            
            # Проверяем общий размер
            if [ ${#combined_content} -gt 25000 ]; then
                gemini_log "⚠️ Достигнут лимит размера, обрабатываю..."
                break
            fi
        fi
    done
    
    gemini_log "📊 Обработано файлов: $file_count"
    
    # Отправляем в Gemini
    result=$(process_with_gemini "$combined_content" "$PROMPT")
    
    # Сохраняем результат
    cat > "$OUTPUT_FILE" << EOF
# Gemini Analysis Result
**Date**: $(date)
**Directory**: $INPUT_PATH
**Files processed**: $file_count
**Prompt**: $PROMPT

---

## Result:

$result

---
*Generated by GalaxyDevelopers Gemini System*
EOF

else
    gemini_log "❌ Путь не найден: $INPUT_PATH"
    exit 1
fi

# Результат
gemini_log "✅ Обработка завершена"
gemini_log "📄 Результат сохранен: $OUTPUT_FILE"

# Показываем первые строки результата
echo ""
echo "Preview:"
echo "--------"
head -20 "$OUTPUT_FILE"
echo "..."
echo ""
echo "Full result: $OUTPUT_FILE"

# Опционально открываем в редакторе
echo ""
echo "Открыть результат? (y/n)"
read -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    open "$OUTPUT_FILE"
fi