# .pre-commit-config.yaml
# Конфигурация для pre-commit хуков

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: ai-code-auditor
        name: AI Code Auditor
        description: Отправляет измененные файлы на проверку AI аудитору через Redis.
        entry: /Volumes/Z7S/development/ALBERT_TOOLS_PLACE/DocumentsSystem/SCRIPTS/git_hook_script.py
        language: script
        stages: [commit]
        # Мы передаем измененные файлы в скрипт
        args: ["--staged"]
