version: '3.8'
services:
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-developer_control}
      POSTGRES_USER: ${POSTGRES_USER:-control_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  ai_auditor:
    build:
      context: .
      dockerfile: Dockerfile.ai-auditor
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_CONNECTION: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-}
    volumes:
      - ./technical_specification.md:/app/tz.md
      - workspace_data:/workspace/target # Changed from bind mount

  web_dashboard:
    build:
      context: .
      dockerfile: Dockerfile.web-dashboard
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_CONNECTION: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  developer_env:
    build:
      context: .
      dockerfile: Dockerfile.developer-isolation
    depends_on:
      - redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - workspace_data:/workspace/target # Changed from bind mount
      - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE

volumes:
  redis_data:
  postgres_data:
  workspace_data: {} # Added named volume